[package]
name = "game"
version = "0.1.0"
authors = ["govind <petrovgovind@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = { version = "0.31.0"}
gl   = "0.10.0"
nalgebra-glm = "0.1"
image = "0.20.0"
